### PR TITLE
LTE: add PSM

### PR DESCRIPTION
**Pull request by peter-pycom**

### CODE REVIEW

**Comment by peter-pycom** [comment]
FW PR: https://github.com/pycom/Firmware-Development/pull/114

**Review by jirkadev — COMMENTED** [review]
LGTM

**Review by jirkadev — DISMISSED** [review]

**Comment by peter-pycom** [comment]
spoke to Catalin, todo:
- document psm() method
- document all (even non-psm) params in init() 
- move example to examples section and elaborate on application. ie, sensor, wake up, long sleep, detach/reattach, power consumption, negotiation with network

**Review by catalinio — APPROVED** [review]
All seems ok.

**Pull request merged**
