### PR TITLE
Update downgrade links to include Pybytes firmware

### PR DESCRIPTION
**Pull request by Xykon**
Add links to Pybytes specific firmware in downgrade.md

### CODE REVIEW

**Comment by jirkadev** [comment]
If I preview the updated markdown page. It seems to be that those links are already there

https://github.com/pycom/pycom-documentation/blob/b4e8b7180916ce2c99522a1d28e1e856a26c6a73/content/advance/downgrade.md

**Comment by Xykon** [comment]
> If I preview the updated markdown page. It seems to be that those links are already there
> 
> https://github.com/pycom/pycom-documentation/blob/b4e8b7180916ce2c99522a1d28e1e856a26c6a73/content/advance/downgrade.md

OK updated.

**Comment by jirkadev** [comment]
Thanks for your changes. I think this would be a bit cleaner structure.
If you the whole sentences as titles, people might miss the firmware versions 

```
Here you can download Pycom firmware:

### Current and previous Pybytes firmware

* [WiPy](https://software.pycom.io/downloads/pybytes/WiPy.html)
* [LoPy](https://software.pycom.io/downloads/pybytes/LoPy.html)
* [SiPy](https://software.pycom.io/downloads/pybytes/SiPy.html)
* [GPy](https://software.pycom.io/downloads/pybytes/GPy.html)
* [FiPy](https://software.pycom.io/downloads/pybytes/FiPy.html)
* [LoPy4](https://software.pycom.io/downloads/pybytes/LoPy4.html)

### Legacy and previous development firmware

* [WiPy](https://software.pycom.io/downloads/WiPy.html)
* [LoPy](https://software.pycom.io/downloads/LoPy.html)
* [SiPy](https://software.pycom.io/downloads/SiPy.html)
* [GPy](https://software.pycom.io/downloads/GPy.html)
* [FiPy](https://software.pycom.io/downloads/FiPy.html)
* [LoPy4](https://software.pycom.io/downloads/LoPy4.html)
```

Screen Shot 2020-02-10 at 16 22 30

If you want I can add a commit with this change to your branch

**Comment by Xykon** [comment]
OK updated

**Review by jirkadev — APPROVED** [review]

**Pull request merged**
