### PR TITLE
Move CoAp documentation to correct location

### PR DESCRIPTION
**Pull request by husigeza**
The CoAp module's documentation is not visible on the webpage perhaps because of the incorrect location.

### CODE REVIEW

**Comment by jirkadev** [comment]
can you test it on localhost if this change fixed the issue, please?

there's a note how to run docs on localhost in the readme.

**Comment by husigeza** [comment]
@jirikrepl : good advice, it is still not visible... What should I add and where to become visible ?
Update: I need to add it into config.toml

**Comment by jirkadev** [comment]
Yes I think that's the file from which is the sidebar generated

**Comment by husigeza** [comment]
@jirikrepl : currently the documentation is visible, however not shown up when searching for it. Do you know how can I make it searchable?

**Comment by jirkadev** [comment]
It might be, that it becomes searchable when it is deployed because it is using google search (which might need some time to build the index).

**Review by jirkadev — APPROVED** [review]

**Pull request merged**
