### PR TITLE
Documentation of RMT class

### PR DESCRIPTION
**Pull request by husigeza**

### CODE REVIEW

**Comment by robert-hh** [comment]
It is good to write documentation, but ... where is the module? There is not machine.RMT class yet.

**Comment by husigeza** [comment]
Check this: https://github.com/pycom/pyupython/pull/5
It was requested by Daniel to initiate the 2 requests in parallel.

Cheers,
Geza

**Comment by robert-hh** [comment]
Sorry, the link you point at cannot be found. https://github.com/pycom/pyupython/pull/5

**Comment by husigeza** [comment]
The implementation of the class is being reviewed currently, the documentation will be checked and reviewed after the feature is merged :) So yes, you are right currently it is not part of the SW.

**Pull request closed without merging**
