### PR TITLE
Pycoproc

### PR DESCRIPTION
**Pull request by gijsio**

### CODE REVIEW

**Comment by peter-pycom** [comment]
I remember we spoke about this the other day in person. Is this now ready for review or WIP?

**Comment by gijsio** [comment]
This is ready for review

**Review by peter-pycom — CHANGES_REQUESTED** [review]
So, I think there are some bigger structural issues. Maybe you want to address them here or in another PR, that's fine. Please let me know.

- How would someone find pycoproc or pycoproc2? It kinda just falls out of the heavens but nobody would ever know to go there. It's not linked from anywhere. I think there should be a logical flow from 
- There is nothing that creates a connection from e.g., Pysense to Accelerometer. How do I know which of the sensors a Pyscan has?!
- I think there should be a useful 'landing page' per shield. Can be short, a picture and short summary and a couple of links (sensors, lib, pycoproc)
- There should be a overview page for the sensors where we link the technical driver/API names to human readable names. In the side navigation in the API section we should use the technical names. That would be consistent with the technical pycoproc name
- Step 4 on getting started page should use the "Shield" language instead of "Expansionboard"


A couple smaller items, which I think should be addressed in this PR:
- we said we wouldn't use the term "pyshields", please reformulate
- I know we said that eventually we want to make releases with individual zip files, but that hasn't happened yet and it's a little more complicated than I thought. Still doable, and still the plan, but it has yet to happen. So for the moment it doesn't make sense to link to the releases page. Instead please link to *the folder* inside the pycom-libraries repository.
- The links in the tutorials & examples section to pycom-libraries subfolder are now broken, e.g. on https://pr-375.d1rmdw1xyxqk1e.amplifyapp.com/tutorials/expansionboards/pysense2/

**Comment by gijsio** [comment]
Thanks for the suggestions. I fixed the ones applicable to the scope of this PR, but we will definitely need to look into the examples and improve the linking there.

**Comment by peter-pycom** [comment]
Still open:

>     * How would someone find pycoproc or pycoproc2? It kinda just falls out of the heavens but nobody would ever know to go there. It's not linked from anywhere. I think there should be a logical flow from
> 
>     * There is nothing that creates a connection from e.g., Pysense to Accelerometer. How do I know which of the sensors a Pyscan has?!
> 
>     * I think there should be a useful 'landing page' per shield. Can be short, a picture and short summary and a couple of links (sensors, lib, pycoproc)
> 


Closed:
>     * There should be a overview page for the sensors where we link the technical driver/API names to human readable names. In the side navigation in the API section we should use the technical names. That would be consistent with the technical pycoproc name
>     * Step 4 on getting started page should use the "Shield" language instead of "Expansionboard"
>     * we said we wouldn't use the term "pyshields", please reformulate
>     * I know we said that eventually we want to make releases with individual zip files, but that hasn't happened yet and it's a little more complicated than I thought. Still doable, and still the plan, but it has yet to happen. So for the moment it doesn't make sense to link to the releases page. Instead please link to _the folder_ inside the pycom-libraries repository.
>     * The links in the tutorials & examples section to pycom-libraries subfolder are now broken, e.g. on https://pr-375.d1rmdw1xyxqk1e.amplifyapp.com/tutorials/expansionboards/pysense2/

**Pull request closed without merging**
