### PR TITLE
fixed-lora-abp-example

### PR DESCRIPTION
**Pull request by jirikrepl**
The code will fail because we haven't imported module binascii

I replaced binascii with ubinascii

### CODE REVIEW

**Comment by Xykon** [comment]
I would suggest using `import binascii` rather than changing the `binascii` call to `ubinascii`

**Comment by jirikrepl** [comment]
why? here they say it has `unhexlify` method implemented as well
http://docs.micropython.org/en/v1.9.3/pyboard/library/ubinascii.html

**Comment by Xykon** [comment]
`binascii` and `ubinascii` are exactly the same thing, except that `binascii` is the official name in python3 so you can do `import binascii` in regular python but you can't use `import ubinascii`

It's probably a philosophical question which one to use... I tend to think it's better to use the official python3 name rather than the micropython name...

**Comment by jirikrepl** [comment]
Alright I think it's fine how it is. @sdaniel55 or anybody feel free to merge it or change it if you want.

**Pull request merged**
